#%RAML 0.8
title: ApiLedConnectivityExample
version: 1.0
baseUri: http://localhost:8080/api

/get-employee-data-prc:
    get:
        description: Process API to process the data received from system api and return to experiencec api
        responses:
            200:
                body:
                    text/plain:
                        example: a,b,c
